[status, result] = system(['powershell -Command "' ...
    'Get-NetIPAddress -AddressFamily IPv4 | ' ...
    'Where-Object {$_.InterfaceAlias -like ''vEthernet (WSL*''} | ' ...
    'Select-Object -First 1 -ExpandProperty IPAddress"']);

if status == 0 && ~isempty(strtrim(result))
    wslVEip = strtrim(result);  % Remove any leading/trailing whitespace
    fprintf('WSL vEthernet IP: %s\n', wslVEip);
else
    wslVEip = '';
    error(['Could not retrieve WSL vEthernet IP. Please re-run initVehicleSIL and enter in your WSL IP' ...
        ' address as an argument, or, start WSL.']);
end
