%% build_FixedwingPlaneAeroCoefficientsModel.m
% Programmatically creates
% vehicle/fixedwing_plane/components/FixedwingPlaneAeroCoefficientsModel.slx --
% a drop-in replacement for vehicle/F16/components/F16AeroCoefficientsModel.slx
% with the EXACT SAME interface contract (so it can be swapped into a clone of
% vehicle/F16/components/aero.slx's "aeroModel" Model Reference block without
% touching anything else in that file):
%
%   Inputs:  alpha_deg, beta_deg, posElevator_deg, posAilerons_deg,
%            posRudder_deg, airspeedInBody_ftps, aircraftAngVelInBody_radps (3x1)
%   Outputs: CF (3x1: CX,CY,CZ body-axis force coefficients)
%            CM (3x1: Cl,Cm,Cn body-axis moment coefficients, nondimensionalized
%                by b/c downstream in aero.slx's sumForcesMoments subsystem)
%
% Unlike F16AeroCoefficientsModel.slx (Stevens & Lewis NASA F-16 wind-tunnel
% polynomial tables, hardcoded to the F-16's exact alpha/beta/deflection
% breakpoint grid), this model implements a SIMPLE LINEAR stability-derivative
% aerodynamic model -- standard textbook formulation (e.g. Etkin, "Dynamics of
% Flight"), not a wind-tunnel-validated dataset. Coefficient values are
% engineering estimates derived from the real geometry of
% LADAC-Examples/Plane/Funray (wingspan b=2.0 m from wing_params_FunrayMain.m;
% wing area/mean chord computed by trapezoidal integration of that file's
% chord/eta_segments_wing station data -- see
% PLAN_VEHICULOS_AEREOS_Y_MARINOS_SITL.md for the worked calculation) combined
% with standard finite-wing lifting-line and typical-tailed-aircraft
% coefficient magnitudes -- NOT a wind-tunnel or panel-method (LADAC) dataset.
% Documented here as an explicit fidelity-level choice, same practice as this
% project's other "reasonable order-of-magnitude, not vendor-validated" vehicle
% parameters (see vehicle/common/setUpVehicle.m's rover cases).
%
% Prerequisites: none beyond a plain MATLAB session (no bus objects needed --
% this model has no Bus inputs/outputs, only plain doubles).
%
% Two gotchas found while building this programmatically (kept here so the
% next build script doesn't rediscover them the hard way):
%   1. A MATLAB Function block's chart.Script MUST have its function
%      signature on a SINGLE line when set via the Stateflow.EMChart API --
%      wrapping the parameter list across multiple lines (even though that is
%      valid plain MATLAB syntax inside unclosed parens) silently corrupts
%      the parsed signature and leaves the block with far fewer ports than
%      the real argument count. Body statements can still be split one per
%      line normally.
%   2. A vector-valued Inport (aircraftAngVelInBody_radps, a 3-vector) needs
%      its 'PortDimensions' set explicitly -- this model is only ever used as
%      a Model Reference (its ports get their real size from whatever wires
%      into it), so leaving PortDimensions at the default -1 (inherited)
%      fails standalone compilation with "underspecified signal dimensions"
%      even though it compiles fine once referenced from aeroFixedwingPlane.slx.

clear; clc;

rootDir = fileparts(mfilename('fullpath'));
modelName = 'FixedwingPlaneAeroCoefficientsModel';
savePath  = fullfile(rootDir, [modelName '.slx']);

if bdIsLoaded(modelName)
    close_system(modelName, 0);
end

new_system(modelName);
set_param(modelName, 'SolverType', 'Fixed-step');

%% ====================================================================
%% INPORTS (order matches F16AeroCoefficientsModel.slx exactly)
%% ====================================================================
add_block('simulink/Sources/In1', [modelName '/alpha_deg'], ...
    'Position', [40, 40, 80, 60], 'Port', '1');
add_block('simulink/Sources/In1', [modelName '/beta_deg'], ...
    'Position', [40, 100, 80, 120], 'Port', '2');
add_block('simulink/Sources/In1', [modelName '/posElevator_deg'], ...
    'Position', [40, 160, 80, 180], 'Port', '3');
add_block('simulink/Sources/In1', [modelName '/posAilerons_deg'], ...
    'Position', [40, 220, 80, 240], 'Port', '4');
add_block('simulink/Sources/In1', [modelName '/posRudder_deg'], ...
    'Position', [40, 280, 80, 300], 'Port', '5');
add_block('simulink/Sources/In1', [modelName '/airspeedInBody_ftps'], ...
    'Position', [40, 340, 80, 360], 'Port', '6');
% Despite the name, aero.slx's calcWindAxes subsystem feeds this as the RAW
% 3-vector relative-wind velocity in body axes (m2ft-converted), not a scalar
% airspeed magnitude -- confirmed by inspecting F16AeroCoefficientsModel.slx's
% real Inport width and aero.slx's calcWindAxes wiring. Must be norm()'d
% inside the MATLAB Function below, not used directly as a scalar.
set_param([modelName '/airspeedInBody_ftps'], 'PortDimensions', '3');
add_block('simulink/Sources/In1', [modelName '/aircraftAngVelInBody_radps'], ...
    'Position', [40, 400, 80, 420], 'Port', '7');
set_param([modelName '/aircraftAngVelInBody_radps'], 'PortDimensions', '3');

%% ====================================================================
%% MATLAB FUNCTION BLOCK
%% ====================================================================
fcn_blk = [modelName '/linearAeroCoefficients'];
add_block('simulink/User-Defined Functions/MATLAB Function', fcn_blk, ...
    'Position', [200, 40, 500, 420]);

%% ====================================================================
%% OUTPORTS
%% ====================================================================
add_block('simulink/Sinks/Out1', [modelName '/CF'], ...
    'Position', [600, 100, 640, 120], 'Port', '1');
add_block('simulink/Sinks/Out1', [modelName '/CM'], ...
    'Position', [600, 300, 640, 320], 'Port', '2');

%% ====================================================================
%% MATLAB FUNCTION SCRIPT (must be set BEFORE add_line on its ports -- a
%% freshly added MATLAB Function block only exposes 1 in/1 out port until
%% the chart script defines the real signature)
%% ====================================================================
open_system(modelName);
pause(0.5);
rt  = sfroot();
mdl = rt.find('-isa', 'Simulink.BlockDiagram', 'Name', modelName);
charts = mdl.find('-isa', 'Stateflow.EMChart');
if isempty(charts)
    warning('Stateflow chart not found. Open the model manually and paste the function code.');
else
    chart = charts(1);
    chart.Script = [ ...
'function [CF, CM] = linearAeroCoefficients(alpha_deg, beta_deg, posElevator_deg, posAilerons_deg, posRudder_deg, airspeedInBody_ftps, aircraftAngVelInBody_radps)' newline ...
'%#codegen' newline ...
'% Linear stability-derivative aero model for a light (Funray-class) ala-fija' newline ...
'% RC/GA airframe. See build_FixedwingPlaneAeroCoefficientsModel.m header and' newline ...
'% PLAN_VEHICULOS_AEREOS_Y_MARINOS_SITL.md for sourcing/derivation of every' newline ...
'% constant below. All constants inlined as local values (not read from a' newline ...
'% struct-returning params function) -- MATLAB Function blocks in this MATLAB' newline ...
'% release fail to compile a call to a large-nested-struct-returning function,' newline ...
'% see optimAeroPX4SIL/CLAUDE.md section 3.' newline ...
'' newline ...
'% Funray-derived reference geometry' newline ...
'bRef_m = 2.0;' newline ...
'cRef_m = 0.1853;' newline ...
'' newline ...
'% Longitudinal linear stability/control derivatives (per rad)' newline ...
'CL0 = 0.05; CLalpha = 5.16; CLde = 0.5; CLq = 7.0;' newline ...
'CD0 = 0.035; kInducedDrag = 0.0347;' newline ...
'Cm0 = 0.02; Cmalpha = -1.0; Cmde = -1.5; Cmq = -15.0;' newline ...
'' newline ...
'% Lateral-directional linear stability/control derivatives (per rad)' newline ...
'CYbeta = -0.5; CYdr = 0.15; CYp = -0.05; CYr = 0.2;' newline ...
'Clbeta = -0.03; Clda = 0.15; Cldr = 0.01; Clp = -0.5; Clr = 0.1;' newline ...
'Cnbeta = 0.08; Cnda = -0.01; Cndr = -0.08; Cnp = -0.02; Cnr = -0.15;' newline ...
'' newline ...
'alpha_rad = deg2rad(alpha_deg);' newline ...
'beta_rad = deg2rad(beta_deg);' newline ...
'elevator_rad = deg2rad(posElevator_deg);' newline ...
'aileron_rad = deg2rad(posAilerons_deg);' newline ...
'rudder_rad = deg2rad(posRudder_deg);' newline ...
'' newline ...
'V_mps = norm(airspeedInBody_ftps) * 0.3048;' newline ...
'VforRates_mps = max(V_mps, 1.0);' newline ...
'pRate_radps = aircraftAngVelInBody_radps(1);' newline ...
'qRate_radps = aircraftAngVelInBody_radps(2);' newline ...
'rRate_radps = aircraftAngVelInBody_radps(3);' newline ...
'pHat = pRate_radps * bRef_m / (2 * VforRates_mps);' newline ...
'qHat = qRate_radps * cRef_m / (2 * VforRates_mps);' newline ...
'rHat = rRate_radps * bRef_m / (2 * VforRates_mps);' newline ...
'' newline ...
'CL = CL0 + CLalpha * alpha_rad + CLde * elevator_rad + CLq * qHat;' newline ...
'CD = CD0 + kInducedDrag * CL^2;' newline ...
'CY = CYbeta * beta_rad + CYdr * rudder_rad + CYp * pHat + CYr * rHat;' newline ...
'' newline ...
'rollMomentCoefficient_nd = Clbeta * beta_rad + Clda * aileron_rad + ...' newline ...
'    Cldr * rudder_rad + Clp * pHat + Clr * rHat;' newline ...
'pitchMomentCoefficient_nd = Cm0 + Cmalpha * alpha_rad + Cmde * elevator_rad + Cmq * qHat;' newline ...
'yawMomentCoefficient_nd = Cnbeta * beta_rad + Cnda * aileron_rad + ...' newline ...
'    Cndr * rudder_rad + Cnp * pHat + Cnr * rHat;' newline ...
'' newline ...
'% Wind-axes (CL,CD) -> body-axes (CX,CZ); CY needs no rotation at this' newline ...
'% linearized fidelity level (small-beta approximation).' newline ...
'CXTotal = -CD * cos(alpha_rad) + CL * sin(alpha_rad);' newline ...
'CZTotal = -CD * sin(alpha_rad) - CL * cos(alpha_rad);' newline ...
'' newline ...
'CF = [CXTotal; CY; CZTotal];' newline ...
'CM = [rollMomentCoefficient_nd; pitchMomentCoefficient_nd; yawMomentCoefficient_nd];' newline ...
'end'];
end

%% ====================================================================
%% CONNECT
%% ====================================================================
fcnName = get_param(fcn_blk, 'Name');
add_line(modelName, 'alpha_deg/1', [fcnName '/1'], 'autorouting', 'on');
add_line(modelName, 'beta_deg/1', [fcnName '/2'], 'autorouting', 'on');
add_line(modelName, 'posElevator_deg/1', [fcnName '/3'], 'autorouting', 'on');
add_line(modelName, 'posAilerons_deg/1', [fcnName '/4'], 'autorouting', 'on');
add_line(modelName, 'posRudder_deg/1', [fcnName '/5'], 'autorouting', 'on');
add_line(modelName, 'airspeedInBody_ftps/1', [fcnName '/6'], 'autorouting', 'on');
add_line(modelName, 'aircraftAngVelInBody_radps/1', [fcnName '/7'], 'autorouting', 'on');
add_line(modelName, [fcnName '/1'], 'CF/1', 'autorouting', 'on');
add_line(modelName, [fcnName '/2'], 'CM/1', 'autorouting', 'on');

%% ====================================================================
%% CONFIG SET -- share the same external ConfigSetRef every other component
%% in this pipeline uses (engineModelF16.slx, aero.slx, etc.), rather than a
%% standalone local config. Requires 'standardSILConfiguraitonParams' (sic,
%% matches the repo-wide typo) to already exist in the base workspace --
%% e.g. via initVehicleSIL, or manually:
%%   load('standardSILConfigurationParams.mat')
%%   assignin('base','standardSILConfiguraitonParams',standardSILConfigurationParams)
%% ====================================================================
if evalin('base', "exist('standardSILConfiguraitonParams','var')") == 1
    configSetRef = Simulink.ConfigSetRef;
    configSetRef.SourceName = 'standardSILConfiguraitonParams';
    attachConfigSet(modelName, configSetRef, true);
    setActiveConfigSet(modelName, configSetRef.Name);
else
    warning(['standardSILConfiguraitonParams not found in base workspace -- ' ...
        'leaving this model on its own local Fixed-step config. Re-run ' ...
        'attachConfigSet/setActiveConfigSet manually once it is loaded.']);
end

%% ---- Save ----------------------------------------------------------
Simulink.BlockDiagram.arrangeSystem(modelName);
save_system(modelName, savePath);
fprintf('\nModel saved: %s\n', savePath);
