function vehicles = vehicleRegistry(vehicleType)
% vehicleRegistry Return supported SIL vehicle definitions.
%
% vehicleRegistry() returns the full registry. vehicleRegistry(vehicleType)
% resolves aliases and returns the matching definition.

vehicles = [
    makeVehicle("F16", "F-16", "vehicle/F16", "setUpVehicle", "BusDefinition", ...
        "F16", "optimAeroF16", "fixedwing", "servos", true, true, true, 120, ...
        ["f16", "f-16"], "F-16", "F16", "F16.mldatx")
    makeVehicle("hexarotor", "Hexarotor", "vehicle/hexarotor", "setUpVehicle", "BusDefinition", ...
        "hexarotor", "optimAeroHex", "multirotor", "motors", true, true, true, 120, ...
        ["hex", "hexarotor"], "hexarotor", "hexarotor", "hexarotor.mldatx")
    makeVehicle("quadrotor", "Quadrotor", "vehicle/quadrotor", "setUpVehicle", "BusDefinition", ...
        "quadrotor", "optimAeroQuad", "multirotor", "motors", true, true, true, 120, ...
        ["quad", "quadrotor"], "hexarotor", "quadrotor", "quadrotor.mldatx")
    makeVehicle("octarotor", "Octarotor", "vehicle/octarotor", "setUpVehicle", "BusDefinition", ...
        "octarotor", "optimAeroOcta", "multirotor", "motors", true, true, true, 120, ...
        ["octa", "octarotor"], "hexarotor", "octarotor", "octarotor.mldatx")
    makeVehicle("evtol", "eVTOL", "vehicle/evtol", "setUpVehicle", "BusDefinition", ...
        "evtol", "optimAeroEVTOL", "multirotor", "motors", true, false, true, 120, ...
        ["evtol", "eVTOL"], "hexarotor", "evtol", "evtol.mldatx")
    makeVehicle("evtol_simscape", "eVTOL Simscape Adapter", "vehicle/evtol_simscape", "setUpVehicle", "BusDefinition", ...
        "evtol_simscape", "optimAeroEVTOL", "multirotor", "motors", true, false, true, 120, ...
        ["evtol_simscape", "evtol_sim"], "hexarotor", "evtol_simscape", "evtol.mldatx")
    makeVehicle("ackermann_rover", "Ackermann Rover", "vehicle/ackermann_rover", "setUpVehicle", "BusDefinition", ...
        "ackermann_rover", "optimAeroAckermann", "rover", "wheels", true, false, true, 120, ...
        ["ackermann", "ackermann_rover", "rover"], "hexarotor", "ackermann_rover", "ackermann_rover.mldatx")
    makeVehicle("ackermann_simscape", "Ackermann Simscape Adapter", "vehicle/ackermann_simscape", "setUpVehicle", "BusDefinition", ...
        "ackermann_simscape", "optimAeroAckermann", "rover", "wheels", true, false, true, 120, ...
        ["ackermann_simscape", "ackermann_sim", "formula_student_simscape"], "hexarotor", "ackermann_simscape", "ackermann_rover.mldatx")
    makeVehicle("differential_rover", "Differential Rover", "vehicle/differential_rover", "setUpVehicle", "BusDefinition", ...
        "differential_rover", "optimAeroDiffRover", "rover", "wheels", true, false, true, 120, ...
        ["diff", "diff_rover", "differential", "differential_rover"], "hexarotor", "differential_rover", "differential_rover.mldatx")
    makeVehicle("tracked_vehicle", "Tracked Vehicle", "vehicle/tracked_vehicle", "setUpVehicle", "BusDefinition", ...
        "tracked_vehicle", "optimAeroTracked", "rover", "tracks", true, false, true, 120, ...
        ["tracked", "tracked_vehicle"], "hexarotor", "tracked_vehicle", "tracked_vehicle.mldatx")
    makeVehicle("tracked_vehicle_simscape", "Tracked Vehicle Simscape Adapter", "vehicle/tracked_vehicle_simscape", "setUpVehicle", "BusDefinition", ...
        "tracked_vehicle_simscape", "optimAeroTracked", "rover", "tracks", true, false, true, 120, ...
        ["tracked_simscape", "tracked_vehicle_simscape", "tracked_sim"], "hexarotor", "tracked_vehicle_simscape", "tracked_vehicle.mldatx")
    makeVehicle("wheel_loader", "Wheel Loader", "vehicle/wheel_loader", "setUpVehicle", "BusDefinition", ...
        "wheel_loader", "optimAeroLoader", "rover", "wheels", true, false, true, 120, ...
        ["loader", "wheel_loader"], "hexarotor", "wheel_loader", "wheel_loader.mldatx")
    makeVehicle("wheel_loader_simscape", "Wheel Loader Simscape Adapter", "vehicle/wheel_loader_simscape", "setUpVehicle", "BusDefinition", ...
        "wheel_loader_simscape", "optimAeroLoader", "rover", "wheels", true, false, true, 120, ...
        ["loader_simscape", "wheel_loader_simscape", "wheel_loader_sim"], "hexarotor", "wheel_loader_simscape", "wheel_loader.mldatx")
    makeVehicle("usv_surface", "USV Surface", "vehicle/usv_surface", "setUpVehicle", "BusDefinition", ...
        "usv_surface", "optimAeroUSV", "boat", "thrusters", true, false, true, 120, ...
        ["usv", "surface", "usv_surface"], "hexarotor", "usv_surface", "usv_surface.mldatx")
    makeVehicle("uuv_subsea", "UUV Subsea", "vehicle/uuv_subsea", "setUpVehicle", "BusDefinition", ...
        "uuv_subsea", "optimAeroUUV", "sub", "thrusters", true, false, true, 120, ...
        ["uuv", "subsea", "uuv_subsea"], "hexarotor", "uuv_subsea", "uuv_subsea.mldatx")
    makeVehicle("bicycle_rover", "Bicycle Rover", "vehicle/bicycle_rover", "setUpVehicle", "BusDefinition", ...
        "bicycle_rover", "optimAeroBicycle", "rover", "wheels", true, false, true, 120, ...
        ["bicycle", "bicycle_rover"], "hexarotor", "bicycle_rover", "bicycle_rover.mldatx")
    makeVehicle("unicycle_rover", "Unicycle Rover", "vehicle/unicycle_rover", "setUpVehicle", "BusDefinition", ...
        "unicycle_rover", "optimAeroUnicycle", "rover", "wheels", true, false, true, 120, ...
        ["unicycle", "unicycle_rover"], "hexarotor", "unicycle_rover", "unicycle_rover.mldatx")
    ];

if nargin == 0 || strlength(string(vehicleType)) == 0
    return
end

query = lower(string(vehicleType));
for ii = 1:numel(vehicles)
    names = lower([vehicles(ii).VehicleKey, vehicles(ii).Aliases]);
    if any(query == names)
        vehicles = vehicles(ii);
        return
    end
end

error("vehicleRegistry:UnknownVehicle", "Unknown vehicle type: %s", string(vehicleType));
end

function vehicle = makeVehicle(vehicleKey, displayName, vehiclePath, setupFunction, busFunction, ...
    plantModel, px4Target, controllerType, actuatorInterface, supportsWaypoints, ...
    supportsFlightGear, supportsGazebo, testTimeoutSeconds, aliases, baseVehicleType, ...
    compileModel, testDefinition)

vehicle = struct( ...
    "VehicleKey", string(vehicleKey), ...
    "DisplayName", string(displayName), ...
    "VehiclePath", string(vehiclePath), ...
    "SetupFunction", string(setupFunction), ...
    "BusFunction", string(busFunction), ...
    "PlantModel", string(plantModel), ...
    "PX4Target", string(px4Target), ...
    "ControllerType", string(controllerType), ...
    "ActuatorInterface", string(actuatorInterface), ...
    "SupportsWaypoints", logical(supportsWaypoints), ...
    "SupportsFlightGear", logical(supportsFlightGear), ...
    "SupportsGazebo", logical(supportsGazebo), ...
    "TestTimeoutSeconds", double(testTimeoutSeconds), ...
    "Aliases", string(aliases), ...
    "BaseVehicleType", string(baseVehicleType), ...
    "CompileModel", string(compileModel), ...
    "TestDefinition", string(testDefinition));
end
